template = "https://github.com/giellalt/template-lang-und"
rev_id = 270
template_sha = "a0e776e00408c682c6560029f0fded3c700e0e63"

[replacements]
__GLOTTOLOG_ID__ = "nucl1301"
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
