template = "https://github.com/giellalt/template-lang-und"
rev_id = 265
template_sha = "55c74340aa57ef2b38d3f84b2a9790e969781f56"

[replacements]
__GLOTTOLOG_ID__ = "nucl1301"
__REPO__ = "lang-tur-x-ext-trmorph"
__UND2C__ = "tr"
__UNDEFINED__ = "Turkish"
__UND__ = "tur"
